POST annotate-backend.cfapps.eu10.hana.ondemand.com/annotation HTTP/1.1
content-type: application/json

{
    "userId": "sampleUser6",
    "taskId": "60bfa444b3dce54f1055b490",
    "annotationProperties": [
        {
            "labels": ["Person"],
            "endPosition": 20,
            "startPosition": 1,
            "entity": "John McEnroe"
        },
        {
            "labels": ["Organization"],
            "endPosition": 100,
            "startPosition": 90,
            "entity": "Fidelity"
        },
        {
            "labels": ["Location"],
            "endPosition": 200,
            "startPosition": 190,
            "entity": "Vancouver"
        }
    ]
}

###

POST annotate-backend.cfapps.eu10.hana.ondemand.com/annotation HTTP/1.1
content-type: application/json

{
    "userId": "sampleUser11",
    "taskId": "60bfa444b3dce54f1055b490",
    "annotationProperties": [
        {
            "labels": ["Person"],
            "endPosition": 20,
            "startPosition": 1,
            "entity": "John McEnroe"
        },
        {
            "labels": ["Person"],
            "endPosition": 100,
            "startPosition": 90,
            "entity": "Fidelity"
        },
        {
            "labels": ["Organization"],
            "endPosition": 200,
            "startPosition": 190,
            "entity": "Vancouver"
        }
    ]
}

###

POST annotate-backend.cfapps.eu10.hana.ondemand.com/annotation HTTP/1.1
content-type: application/json

{
    "userId": "sampleUser6",
    "taskId": "60bfa444b3dce54f1055b491",
    "annotationProperties": [
        {
            "labels": ["Person"],
            "endPosition": 20,
            "startPosition": 1,
            "entity": "John McEnroe"
        },
        {
            "labels": ["Organization"],
            "endPosition": 100,
            "startPosition": 90,
            "entity": "Fidelity"
        }
    ]
}

###

POST annotate-backend.cfapps.eu10.hana.ondemand.com/annotation HTTP/1.1
content-type: application/json

{
    "userId": "sampleUser11",
    "taskId": "60bfa444b3dce54f1055b491",
    "annotationProperties": [
        {
            "labels": ["Person"],
            "endPosition": 20,
            "startPosition": 1,
            "entity": "John McEnroe"
        },
        {
            "labels": ["Location"],
            "endPosition": 100,
            "startPosition": 90,
            "entity": "Fidelity"
        }
    ]
}