POST http://localhost:4003/annotation HTTP/1.1
content-type: application/json

{
    "userId": "sampleUser5",
    "taskId": "60bfa444b3dce54f1055b490",
    "annotationProperties": [
        {
            "labels": ["Person"],
            "endPosition": 20,
            "startPosition": 1,
            "entity": "John McEnroe"
        },
        {
            "labels": ["Person"],
            "endPosition": 20,
            "startPosition": 1,
            "entity": "John McEnroe"
        },
        {
            "labels": ["Person"],
            "endPosition": 20,
            "startPosition": 1,
            "entity": "John McEnroe"
        }
    ]
}